name: expresiones
run-name: Â¡Aprendiendo expresiones!
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer 
      nombre:
        description: 'Nombre'
        required: true
        default: 'Jhordan'
        type: string
      lp:
        description: 'LP favorito'
        required: true
        default: 'Java'
        type: choice
        options: ['Java', 'Python', 'Go', 'Shell Script']
      #tag:
      #  description: 'Test scenario tags'
      #  required: false
      #  type: boolean
      environment:
        description: 'Environment to run test against'
        required: true
        type: environment
        options: ['staging', 'dev', 'cert', 'prod']
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer Checkout
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v5
      - name: Definir LANGUAGE
        run: echo "LANGUAGE=${{ inputs.lps }}" >> $GITHUB_ENV
      - name: Definir NOMBRE
        run: echo "NOMBRE=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: Definir LP    
        run: echo "LP=${{ inputs.lp }}" >> $GITHUB_ENV
    #  - name: Definir TAG    
    #    run: echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
      - name: Definir ENVIRONMENT    
        run: echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
      - name: Run File Python
        run: python expresiones.py
          
          
