name: expresioness
run-name: Â¡Aprendiendo expresiones!
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Nombre'
        required: true
        default: 'Jhordan'
        type: string
      age:
        description: 'Age'
        required: true
        type: string
      lp:
        description: 'LP favorito'
        required: true
        default: 'Java'
        type: choice
        options: ['Java', 'Python', 'Go', 'Shell Script']
      sex:
         description: 'Sex'
         required: true
         type: choice
         options: ['male', 'female']
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer Checkout
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v5
      - name: Definir NAME
        run: echo "NAME=${{ inputs.name }}" >> $GITHUB_ENV
      - name: Definir AGE
        run: echo "AGE=${{ inputs.age }}" >> $GITHUB_ENV
      - name: Definir SEX
        run: echo "SEX=${{ inputs.sex }}" >> $GITHUB_ENV
      - name: Definir LP    
        run: echo "LP=${{ inputs.lp }}" >> $GITHUB_ENV
      - name: Run File Python
        run: python expresiones.py
          
          
